import { createFileRoute } from "@tanstack/react-router";
import { AlertTriangle, Eye, FileSearch, Lock, ShieldCheck } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { AiNotice, PageHeader, SectionCard } from "@/components/ui-kit";

export const Route = createFileRoute("/responsible-ai")({
  head: () => ({
    meta: [
      { title: "Responsible AI | AI Workplace Productivity Assistant" },
      {
        name: "description",
        content:
          "How this assistant handles AI-generated content, human review, privacy, accuracy and sources.",
      },
      { property: "og:title", content: "Responsible AI practices" },
      {
        property: "og:description",
        content: "Human review, privacy, accuracy and honest sourcing in every AI tool.",
      },
    ],
  }),
  component: ResponsibleAi,
});

const sections = [
  {
    icon: AlertTriangle,
    title: "AI-generated content",
    body: "Every output in this application is generated by an AI model. It may contain errors, omissions or incorrect assumptions, and it can sound confident while being wrong. Treat each result as a first draft rather than a finished deliverable.",
  },
  {
    icon: Eye,
    title: "Human review",
    body: "Review AI-generated content before you send an email, make a decision, publish information or rely on a recommendation. You remain responsible for what leaves your desk. Where a result affects people, budgets or commitments, have a second person check it.",
  },
  {
    icon: Lock,
    title: "Privacy",
    body: "Do not enter confidential, sensitive, proprietary, financial or personal information, and never enter passwords or credentials, unless your organisation's policy explicitly permits it. Anonymise names and client details where you can.",
  },
  {
    icon: FileSearch,
    title: "Accuracy",
    body: "AI output should not automatically be treated as verified information. Figures, dates, names and quoted commitments must be checked against your own records before use.",
  },
  {
    icon: ShieldCheck,
    title: "Sources",
    body: "This assistant never fabricates citations and never pretends that information has been externally verified. It has no live web access, so research results are based on the material you provide plus the model's existing knowledge. When AI is not configured, results are clearly labelled as demonstration content.",
  },
];

function ResponsibleAi() {
  return (
    <AppShell>
      <PageHeader
        title="Responsible AI"
        subtitle="How this assistant is designed to be used safely at work."
      />

      <div className="grid grid-cols-1 gap-5 lg:grid-cols-2">
        {sections.map(({ icon: Icon, title, body }) => (
          <SectionCard
            key={title}
            title={title}
            icon={<Icon className="size-[18px]" aria-hidden="true" />}
          >
            <p className="text-sm leading-relaxed text-muted-foreground">{body}</p>
          </SectionCard>
        ))}
      </div>

      <SectionCard title="What this assistant will not do" className="mt-5">
        <ul className="grid gap-2.5 text-sm leading-relaxed text-muted-foreground sm:grid-cols-2">
          {[
            "Invent names, dates, deadlines or commitments you did not supply.",
            "Fabricate citations, URLs, publications or statistics.",
            "Claim that a demonstration response came from a live AI service.",
            "Make high-stakes professional decisions on your behalf.",
            "Present inference as explicitly stated fact.",
            "Schedule work outside the hours you say you are available.",
          ].map((item) => (
            <li key={item} className="flex gap-2.5">
              <span
                className="mt-1.5 size-1.5 shrink-0 rounded-full bg-primary"
                aria-hidden="true"
              />
              <span className="min-w-0">{item}</span>
            </li>
          ))}
        </ul>
      </SectionCard>

      <AiNotice className="mt-6" />
    </AppShell>
  );
}
